### ISSUE TITLE
[Suggestion] Add a config to allow us to enable/disable each change individually

### ISSUE THREAD

**Issue by vizthex123** [violn/niols-Buffed-Accessories-Mod#6]
I posted it on the workshop page, but figured I should put it here too.

**Comment by violn** [comment]
They first config option has been added.

**Comment by violn** [comment]
I'll make the rest shortly.

**Comment by violn** [comment]
Ok I'm done with the update tell me if you find any bugs.

**Comment by vizthex123** [comment]
noice, thanks
